<?php
/**
 * [roden_chart] — render a research chart from a versioned SVG in the theme.
 *
 * WHY A SHORTCODE AND NOT INLINE SVG. The Corridor Report's charts were first
 * written straight into post_content. They render correctly, but wp_kses_post()
 * strips <svg> wholesale — so the moment anyone without the unfiltered_html
 * capability opens the post in wp-admin and saves it, both charts vanish and take
 * about 4 KB of the report with them. Silently: no error, no warning, and the
 * prose around them still reads as though a chart were there.
 *
 * Administrators on a single site have unfiltered_html, so it would have survived
 * a while and then broken for the first editor who touched it. A shortcode is
 * plain text to KSES and passes through untouched.
 *
 * Keeping the SVG in the theme rather than the database also means the charts are
 * version-controlled, reviewable in a diff, and regenerated by
 * bin/corridor-report-charts.py rather than hand-edited in a textarea.
 *
 * Usage:  [roden_chart name="corridor-truck-share"]
 *         [roden_chart name="corridor-by-year" caption="Fatal crashes per year"]
 *
 * @package RodenLaw
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Render a named chart.
 *
 * @param array $atts name, optional caption.
 * @return string Figure markup, or '' if the chart does not exist.
 */
function roden_chart_shortcode( $atts ) {
    $atts = shortcode_atts( array( 'name' => '', 'caption' => '' ), $atts, 'roden_chart' );

    // Whitelist the filename shape. The name reaches the filesystem, so anything
    // outside [a-z0-9-] is rejected rather than sanitised — a traversal attempt
    // should fail loudly in the logs, not quietly resolve to something adjacent.
    if ( ! preg_match( '/^[a-z0-9-]+$/', $atts['name'] ) ) {
        return '';
    }

    $file = get_template_directory() . '/assets/charts/' . $atts['name'] . '.svg';
    if ( ! file_exists( $file ) ) {
        return '';
    }

    $svg = file_get_contents( $file );
    if ( false === $svg || '' === trim( $svg ) ) {
        return '';
    }

    $caption = '' !== $atts['caption']
        ? '<figcaption>' . esc_html( $atts['caption'] ) . '</figcaption>'
        : '';

    return '<figure class="research-chart">' . $svg . $caption . '</figure>';
}
add_shortcode( 'roden_chart', 'roden_chart_shortcode' );
