<?php
/**
 * ES Seeder — Batch 29: Resource — SC Personal Injury FAQ hub (Spanish).
 *
 * CURATED SUBSET: the EN hub (south-carolina-personal-injury-faq) carries the
 * full 95-Q categorized set (inc/data/sc-pi-faq-hub-v2.json). This Spanish
 * version translates the intro and curates the ~20 highest-value Q&As —
 * prioritizing deadlines, cost/fees, case value, insurance dealings, workers
 * comp, and immigration status — rather than mirroring all 95.
 *
 * Run: echo "include get_template_directory() . '/inc/es/es-seed-lib.php'; include get_template_directory() . '/inc/es/seed-es-batch-29-res-faq-hub.php';" | wp eval-file -
 *
 * @package Roden_Law
 */

if ( ! defined( 'ABSPATH' ) ) { exit; }

WP_CLI::log( '═══ ES BATCH 29 — RESOURCE: FAQ HUB ═══' );

$en = get_page_by_path( 'south-carolina-personal-injury-faq', OBJECT, 'resource' );
if ( $en ) {
    roden_es_seed_translation( $en->ID, array(
        'title'   => 'Preguntas Frecuentes sobre Lesiones Personales en Carolina del Sur',
        'excerpt' => 'Respuestas a las preguntas más comunes sobre lesiones personales en Carolina del Sur: plazos, culpa, valor del caso, seguros, compensación laboral y honorarios de abogados.',
        'content' => <<<'HTML'
<p>Si resultó lesionado en Carolina del Sur, seguramente tiene preguntas urgentes: ¿Cuánto tiempo tengo para demandar? ¿Qué pasa si el choque fue parcialmente mi culpa? ¿Cuánto vale mi caso? ¿Necesito un abogado? ¿Mi estatus migratorio es un problema? Abajo, Roden Law responde en lenguaje sencillo las preguntas más comunes. Estas respuestas describen específicamente la <strong>ley de Carolina del Sur</strong>.</p>
<p>Esta página es un punto de partida, no asesoría legal para su situación específica. Cada caso es diferente. Si quiere respuestas adaptadas a su caso, un abogado de Roden Law lo revisará gratis y en español — y trabajamos con honorarios de contingencia, así que no hay honorarios a menos que ganemos.</p>
<h2>Preguntas sobre lesiones personales en Carolina del Sur, respondidas</h2>
<p>Las preguntas siguientes cubren lo que las personas lesionadas más buscan: plazos, culpa, valor del caso, seguros, facturas médicas, compensación laboral y cómo trabajar con un abogado. Para guías más profundas, vea el <a href="/es/resources/south-carolina-statute-of-limitations/">plazo legal para demandar en Carolina del Sur</a> y la regla de <a href="/es/resources/south-carolina-comparative-negligence/">negligencia comparativa</a>.</p>
<h2>¿Todavía tiene preguntas? Hable con un abogado</h2>
<p>Si su pregunta no está respondida aquí — o quiere saber cuánto vale su caso específico — un abogado de Roden Law revisará su situación sin costo. <a href="/es/contact/">Contáctenos</a> o llame al <a href="tel:+18447378587">1-844-RESULTS</a>. No hay honorarios a menos que ganemos.</p>
HTML,
        'meta'    => array(
            '_roden_meta_description' => 'Preguntas frecuentes sobre lesiones personales en Carolina del Sur: plazos, culpa, valor del caso, seguros, compensación laboral y estatus migratorio. En español.',
            '_roden_key_takeaways'    => 'En Carolina del Sur generalmente tiene 3 años para presentar un reclamo por lesiones personales (S.C. Code § 15-3-530), y puede recuperar compensación mientras su culpa sea menor al 51%. No existe un acuerdo "promedio" fijo — el valor depende de sus lesiones, sus pérdidas, la culpa y el seguro disponible. Nunca está obligado a contratar a un abogado, pero los reclamantes representados típicamente recuperan significativamente más, y Roden Law trabaja por contingencia, así que no hay honorarios a menos que ganemos. Su estatus migratorio no le impide reclamar compensación. Las respuestas siguientes cubren las preguntas que las víctimas de lesiones en Carolina del Sur hacen con más frecuencia.',
            '_roden_faqs'             => array(
                array( 'question' => '¿Cuánto tiempo tengo para presentar un reclamo por lesiones personales en Carolina del Sur?', 'answer' => 'Generalmente tiene 3 años desde la fecha de la lesión para presentar una demanda por lesiones personales bajo el S.C. Code § 15-3-530. Los reclamos contra entidades del gobierno tienen un plazo más corto, y la negligencia médica tiene reglas especiales de descubrimiento y reposo. Como dejar pasar el plazo normalmente elimina su reclamo por completo, confirme su plazo específico con un abogado cuanto antes.' ),
                array( 'question' => '¿Cuál es el plazo para demandar al gobierno en Carolina del Sur?', 'answer' => 'Los reclamos contra entidades del gobierno caen bajo la Ley de Reclamos por Agravios de Carolina del Sur y generalmente deben presentarse dentro de 2 años. La ventana se extiende a 3 años solo si presenta un "verified claim" opcional ante la agencia dentro de 1 año de la lesión. Como este plazo es más corto que la regla ordinaria de 3 años, contacte a un abogado de inmediato si una ciudad, un condado o el estado puede ser responsable.' ),
                array( 'question' => '¿Cuál es el plazo para un reclamo por muerte por negligencia en Carolina del Sur?', 'answer' => 'Un reclamo por muerte por negligencia generalmente debe presentarse dentro de 3 años desde la fecha del fallecimiento y debe presentarlo el representante personal del patrimonio de la persona fallecida (S.C. Code § 15-51-20). Como las reglas sobre quién puede presentar y cómo se distribuyen los daños son específicas, las familias deben consultar a un abogado pronto.' ),
                array( 'question' => '¿Qué pasa si dejo pasar el plazo legal en Carolina del Sur?', 'answer' => 'Si presenta la demanda después del plazo, el tribunal casi siempre la desestimará y usted pierde el derecho a recuperar, sin importar qué tan fuertes sean los hechos. Existen unas pocas excepciones estrechas que pueden pausar el reloj, como los reclamos de menores de edad, pero nunca debe confiar en una excepción. Lo más seguro es hablar con un abogado mucho antes de los 3 años.' ),
                array( 'question' => '¿Puedo recuperar compensación si el accidente fue parcialmente mi culpa?', 'answer' => 'Sí. Carolina del Sur usa la negligencia comparativa modificada con barrera del 51%. Puede recuperar mientras su culpa sea 50% o menos, pero su compensación se reduce según su porcentaje de culpa. Por ejemplo, en un caso de $200,000 donde tiene 25% de culpa, recupera $150,000. Con 51% o más de culpa, no recupera nada.' ),
                array( 'question' => '¿Es Carolina del Sur un estado "no-fault" para accidentes de auto?', 'answer' => 'No. Carolina del Sur es un estado de responsabilidad por culpa ("at-fault"), no un estado no-fault. El conductor que causó el choque — y su aseguradora — responde por las lesiones y daños resultantes. Esto es distinto de los estados no-fault, donde usted acude primero a su propia aseguradora sin importar quién causó el choque.' ),
                array( 'question' => '¿Cuánto vale mi caso de lesiones personales en Carolina del Sur?', 'answer' => 'No hay un promedio fijo. El valor depende de la gravedad de sus lesiones, sus facturas médicas e ingresos perdidos totales, el impacto en su vida, su porcentaje de culpa y la cobertura de seguro disponible. Los casos van desde unos miles de dólares por lesiones menores hasta siete cifras por lesiones catastróficas. Un abogado puede darle un estimado honesto tras revisar los hechos.' ),
                array( 'question' => '¿Qué tipos de compensación puedo recuperar en Carolina del Sur?', 'answer' => 'Puede recuperar daños económicos (facturas médicas, salarios perdidos, capacidad de ganancia reducida, daños a la propiedad) y daños no económicos (dolor y sufrimiento, angustia emocional, pérdida del disfrute de la vida, desfiguración). En casos de conducta especialmente grave, también pueden estar disponibles daños punitivos. El total depende de la gravedad de sus lesiones y la fuerza de la evidencia.' ),
                array( 'question' => '¿Hay un tope de daños en los casos de lesiones personales en Carolina del Sur?', 'answer' => 'En casos ordinarios como choques de auto y camión, no hay tope sobre los daños compensatorios — tanto los económicos como los no económicos van sin tope. Carolina del Sur limita los daños punitivos y limita los daños no económicos específicamente en casos de negligencia médica, pero ese tope no aplica a los reclamos ordinarios por negligencia.' ),
                array( 'question' => '¿Qué pasa si me lesionó un conductor sin seguro en Carolina del Sur?', 'answer' => 'Todavía puede recuperar a través de su propia cobertura de motorista sin seguro (UM), que Carolina del Sur exige en toda póliza de auto. La cobertura UM paga por sus lesiones cuando el conductor culpable no tiene seguro. Además, Carolina del Sur permite acumular ("stack") cobertura UM/UIM de varios vehículos o pólizas — haga que un abogado revise cada póliza aplicable.' ),
                array( 'question' => '¿Cuáles son los límites mínimos de seguro de auto en Carolina del Sur?', 'answer' => 'Carolina del Sur exige límites mínimos de responsabilidad de $25,000 por persona y $50,000 por accidente por lesiones corporales, más $25,000 por daños a la propiedad (escrito 25/50/25), y cobertura UM equivalente (S.C. Code § 38-77-140). Estos mínimos son bajos frente al costo de una lesión grave, por eso la acumulación de UM/UIM y cada póliza disponible importan tanto.' ),
                array( 'question' => '¿Debo aceptar la primera oferta de la aseguradora?', 'answer' => 'Usualmente no. Las primeras ofertas suelen estar muy por debajo del valor completo del reclamo y se hacen antes de que usted entienda plenamente sus lesiones y costos futuros. Una vez que acepta y firma la liberación, no puede reabrir el reclamo. Es prudente que un abogado evalúe cualquier oferta antes de aceptarla.' ),
                array( 'question' => '¿Debo dar una declaración grabada a la aseguradora?', 'answer' => 'Hable primero con un abogado. Los ajustadores usan las declaraciones grabadas para fijarlo en palabras tempranas que luego usan para minimizar sus lesiones o trasladarle la culpa. Generalmente no está obligado a dar una declaración grabada a la aseguradora del conductor culpable. Deje que su abogado maneje las comunicaciones.' ),
                array( 'question' => '¿Quién paga mis facturas médicas después de un accidente?', 'answer' => 'A corto plazo, su seguro de salud, la cobertura MedPay o pagos de su bolsillo suelen cubrir el tratamiento. Al final, si otra parte tuvo la culpa, su seguro de responsabilidad debe reembolsar sus gastos médicos como parte de su reclamo. Un abogado puede coordinar estas fuentes y perseguir el reembolso completo de la parte culpable.' ),
                array( 'question' => '¿Tengo que probar que mi empleador tuvo la culpa para recibir compensación laboral?', 'answer' => 'No. La compensación laboral de Carolina del Sur es un sistema sin culpa: generalmente puede recibir beneficios por una lesión laboral sin importar quién tuvo la culpa. A cambio, los beneficios se limitan a cosas como atención médica y reemplazo salarial, no dolor y sufrimiento. Sí debe demostrar que la lesión surgió de su empleo y en el curso del mismo.' ),
                array( 'question' => '¿Qué tan pronto debo reportar una lesión de trabajo en Carolina del Sur?', 'answer' => 'Reporte la lesión a su empleador lo antes posible, y a más tardar 90 días después del accidente (S.C. Code § 42-15-20). Reportar tarde puede poner en riesgo sus beneficios. Luego generalmente tiene 2 años desde la lesión para presentar un reclamo formal ante la Comisión de Compensación Laboral (S.C. Code § 42-15-40).' ),
                array( 'question' => '¿Cuánto paga la compensación laboral en Carolina del Sur?', 'answer' => 'Por incapacidad total, Carolina del Sur paga dos tercios (66⅔%) de su salario semanal promedio, sujeto a un máximo estatal que se fija cada año — $1,189.94 por semana para 2026 — y un mínimo de $75. Hay un período de espera de 7 días, y esos primeros días se pagan retroactivamente si su incapacidad dura más de 14 días (S.C. Code § 42-9-200).' ),
                array( 'question' => '¿Puedo elegir mi propio médico en un caso de compensación laboral en Carolina del Sur?', 'answer' => 'Usualmente no. En la compensación laboral de Carolina del Sur, el empleador o su aseguradora generalmente dirige su atención y elige al médico tratante autorizado. Ver a un médico no autorizado por su cuenta puede significar que esas facturas no se cubran. Si cree que la atención autorizada es inadecuada, un abogado puede ayudarle a buscar un cambio o una segunda opinión por los canales adecuados.' ),
                array( 'question' => '¿Qué puedo hacer si niegan mi reclamo de compensación laboral?', 'answer' => 'Una negación no es el final. Puede solicitar una audiencia ante un Comisionado individual y, si es necesario, apelar al Panel de Apelaciones dentro de 14 días con el Formulario 30, luego a la Corte de Apelaciones de Carolina del Sur dentro de 30 días, y finalmente a la Corte Suprema. Como la escalera de apelación tiene plazos estrictos, involucre a un abogado rápidamente tras la negación.' ),
                array( 'question' => '¿Puedo reclamar compensación si no tengo estatus migratorio legal?', 'answer' => 'Su estatus migratorio no le impide reclamar compensación por sus lesiones en Carolina del Sur — ni en un caso de lesiones personales ni en uno de compensación laboral. Las aseguradoras a veces usan el miedo al estatus para presionar a los trabajadores lesionados a abandonar reclamos válidos. Su consulta con Roden Law es confidencial y en español.' ),
                array( 'question' => '¿Cuánto cuesta un abogado de lesiones personales en Carolina del Sur?', 'answer' => 'Roden Law maneja los casos de lesiones personales con honorarios de contingencia: no paga honorarios por adelantado y no debe nada a menos que ganemos. Nuestro honorario es un porcentaje de la recuperación. Si no ganamos, no paga honorarios de abogado. Esto permite que cualquier persona acceda a representación experimentada sin importar sus finanzas.' ),
                array( 'question' => '¿Necesito un abogado para mi reclamo por lesiones en Carolina del Sur?', 'answer' => 'La ley no le exige contratar a un abogado, pero los reclamantes representados típicamente recuperan significativamente más, incluso después de los honorarios. Las aseguradoras tienen ajustadores y abogados trabajando para minimizar su pago. Un abogado investiga, valora su reclamo con precisión, maneja a las aseguradoras y litiga si es necesario. Roden Law trabaja por contingencia: no paga nada a menos que ganemos.' ),
            ),
        ),
    ) );
} else { WP_CLI::warning( 'EN resource south-carolina-personal-injury-faq not found.' ); }

WP_CLI::log( '═══ BATCH 29 DONE ═══' );
